inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'red-arrow.gemspec'
  SuggestExtensions: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/IfUnlessModifier:
  Enabled: false

Style/Not:
  Enabled: false

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
